#Ansible is agentless and uses YAML playbooks to automate tasks across many devices.

- name: Gather hostname from Cisco routers
  hosts: cisco
  gather_facts: no
  tasks:
    - name: Run show version
      ios_command:
        commands: show version
      register: output
    - debug:
        var: output.stdout_lines